# Site settings
title: Shoreline UI.
email: pigsrule@qq.com
description: React components.
baseurl: "/shoreline-ui"
url: "http://linzerui.github.io/shoreline-ui/" # the base hostname & protocol for your site
github_username:  linzerui

# Build settings
markdown: kramdown
permalink: none
