# Site settings
title: Shoreline UI.
email: pigsrule@qq.com
description: React components.
baseurl: ""
url: "http://linzerui.github.io/shoreline-ui"
github_username:  linzerui

# Build settings
markdown: kramdown
permalink: none
